#!/bin/sh
#
while read file
do
	case "$1" in
	"C-w")
		ln -sf "$HOME/$file" "$HOME/.config/wallpaper/current-wallpaper.png" &&
		feh --bg-fill --no-xinerama "$HOME/.config/wallpaper/current-wallpaper.png"
		;;
	"C-t")
		notify-send "file reads: $file"
		;;
	"C-r")
		name="$(dmenu -p "Rename file to: ")" 2> /dev/null
		if ! [ -z "$name" ] ; then
			mv "$file" "$name"
		fi
		;;
	esac
done
